feat: atualizar episódio atual para 4; melhorar verificação de episódios disponíveis no workflow

diff --git a/.github/workflows/01_init.yaml b/.github/workflows/01_init.yaml
--- a/.github/workflows/01_init.yaml
+++ b/.github/workflows/01_init.yaml
@@ -27,25 +27,26 @@ jobs:
         with:
           python-version: "3.13"
 
-      - name: check if episode is available
+      - name: Check if episode is available
         run: |
-          if [ -f "frame_counter.txt" ]; then
-            current_episode=$(grep "^current_episode:" "frame_counter.txt" | cut -d ':' -f2 | tr -d ' ')
+          current_episode=$(grep "^current_episode:" "frame_counter.txt" | cut -d ':' -f2 | tr -d ' ')
 
-            if [ -z "$current_episode" ]; then
-              echo "current_episode not found in frame_counter.txt."
-              exit 1
-            fi
-
-            episode_count=$(find "episodes/frames" -mindepth 1 -maxdepth 1 -type d | wc -l)
-
-            if [ "$current_episode" -gt "$episode_count" ]; then
-              echo "No more episodes available."
-              exit 1
-              fi
+          if [ -z "$current_episode" ]; then
+            echo "Error: current_episode not found or empty in frame_counter.txt"
+            exit 1
           fi
-      
-      # if you need to install imageMagick
+
+          if [ "$current_episode" -lt 10 ]; then
+            current_episode="0$current_episode"
+          fi
+
+          if [ ! -d "episodes/frames/$current_episode" ]; then
+            echo "No more episodes"
+            exit 1
+          fi
+
+      # install if needed
+
       # - name: install imageMagick
       #   run: |
       #     sudo apt-get update
@@ -53,7 +54,7 @@ jobs:
       
       - name: Install dependencies
         run: |
-          python -m pip install --upgrade pip
+          python -m pip install --upgrade pip 
           pip install -r requirements.txt
 
       - name: Main
