chore: aprimorar workflow de instalação de dependências e atualização do pip

diff --git a/.github/workflows/init.yaml b/.github/workflows/init.yaml
--- a/.github/workflows/init.yaml
+++ b/.github/workflows/init.yaml
@@ -29,22 +29,21 @@ jobs:
             ~/.local/lib/python3.13/site-packages
           key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
           restore-keys: |
-            ${{ runner.os }}-python-
+            ${{ runner.os }}-pip-
 
       - name: Setup Python
         uses: actions/setup-python@v3
         with:
           python-version: 3.13
           architecture: x64
-
+      
+      - name: Upgrade pip to latest stable
+        run: |
+          python -m pip install --upgrade pip || { echo 'Pip upgrade failed'; exit 1; }
+      
       - name: Install dependencies
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
-            
-      - name: Run script
-        run: |
-          python main.py
+          python -m pip install -r requirements.txt || { echo 'Dependency installation failed'; exit 1; }
 
       - name: Commit changes
         uses: stefanzweifel/git-auto-commit-action@v5
